pipeline {
    agent any
     parameters {
        string(defaultValue: "http://localhost:9080", description: 'URL for SonarQube', name: 'SONAR_HOST_URL')
        string(defaultValue: "www-proxy.us.oracle.com", description: 'URL for SonarQube', name: 'PROXY_URL')
        string(defaultValue: "80", description: 'Proxy URL', name: 'PROXY_PORT')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven'
        jdk 'JDK 1.8'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'https://github.com/UligannaVadde/DevOpsDemo.git',
                    credentialsId: '32a9518d-eaf7-421b-90bd-2f5e5fbbaebf'
                )
            }
            
            }
    }
}
